-- MySQL Script generated by MySQL Workbench
-- Sat Aug 19 19:24:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myblog` ;

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myblog` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `myblog` ;

-- -----------------------------------------------------
-- Table `myblog`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`category` ;

CREATE TABLE IF NOT EXISTS `myblog`.`category` (
                                                   `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                   `title` VARCHAR(255) NOT NULL,
    `content` VARCHAR(255) NOT NULL,
    `slug` VARCHAR(255) NULL DEFAULT NULL,
    `created_by` VARCHAR(255) NULL DEFAULT NULL,
    `updated_by` VARCHAR(255) NULL DEFAULT NULL,
    `created_at` DATETIME(6) NULL DEFAULT NULL,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myblog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`user` ;

CREATE TABLE IF NOT EXISTS `myblog`.`user` (
                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                               `user_name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NULL DEFAULT NULL,
    `password` VARCHAR(255) NOT NULL,
    `created_by` VARCHAR(255) NULL DEFAULT NULL,
    `updated_by` VARCHAR(255) NULL DEFAULT NULL,
    `created_at` DATETIME(6) NULL DEFAULT NULL,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myblog`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`post` ;

CREATE TABLE IF NOT EXISTS `myblog`.`post` (
                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                               `title` VARCHAR(255) NOT NULL,
    `slug` VARCHAR(255) NULL DEFAULT NULL,
    `content` VARCHAR(255) NULL DEFAULT NULL,
    `created_by` VARCHAR(255) NULL DEFAULT NULL,
    `updated_by` VARCHAR(255) NULL DEFAULT NULL,
    `created_at` DATETIME(6) NULL DEFAULT NULL,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    `user_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_post_user1_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `myblog`.`user` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myblog`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`comment` ;

CREATE TABLE IF NOT EXISTS `myblog`.`comment` (
                                                  `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                  `content` VARCHAR(255) NULL DEFAULT NULL,
    `created_by` VARCHAR(255) NULL DEFAULT NULL,
    `updated_by` VARCHAR(255) NULL DEFAULT NULL,
    `created_at` DATETIME(6) NULL DEFAULT NULL,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    `user_id` BIGINT NOT NULL,
    `post_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`, `user_id`, `post_id`),
    INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_comment_post1_idx` (`post_id` ASC) VISIBLE,
    CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `myblog`.`post` (`id`),
    CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `myblog`.`user` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myblog`.`post_has_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`post_has_category` ;

CREATE TABLE IF NOT EXISTS `myblog`.`post_has_category` (
                                                            `post_id` BIGINT NOT NULL,
                                                            `category_id` BIGINT NOT NULL,
                                                            PRIMARY KEY (`post_id`, `category_id`),
    INDEX `fk_post_has_category_category1_idx` (`category_id` ASC) VISIBLE,
    INDEX `fk_post_has_category_post1_idx` (`post_id` ASC) VISIBLE,
    CONSTRAINT `fk_post_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `myblog`.`category` (`id`),
    CONSTRAINT `fk_post_has_category_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `myblog`.`post` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myblog`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`role` ;

CREATE TABLE IF NOT EXISTS `myblog`.`role` (
                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                               `name` VARCHAR(255) NOT NULL,
    `created_by` VARCHAR(255) NULL DEFAULT NULL,
    `updated_by` VARCHAR(255) NULL DEFAULT NULL,
    `created_at` DATETIME(6) NULL DEFAULT NULL,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `myblog`.`user_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`user_has_role` ;

CREATE TABLE IF NOT EXISTS `myblog`.`user_has_role` (
                                                        `role_id` BIGINT NOT NULL,
                                                        `user_id` BIGINT NOT NULL,
                                                        PRIMARY KEY (`role_id`, `user_id`),
    INDEX `fk_role_has_user_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_role_has_user_role_idx` (`role_id` ASC) VISIBLE,
    CONSTRAINT `fk_role_has_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `myblog`.`role` (`id`),
    CONSTRAINT `fk_role_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `myblog`.`user` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
